# Output directory for plots
output_dir: "report/base"

# Window size for smoothing
window_size: 50

# Whether to show standard deviation
show_std: true

# Figure size
figsize: [8, 6]

# Metrics to plot
metrics_to_plot:
  - loss

# Experiment definitions
experiments:
  - name: "E2E - Base"
    path: "output/e2e_spec_aug_base"

  - name: "LoRA - Base"
    path: "output/r_254_a_128_d_025_spec_aug_base" 