dataset_config:
  train:
    datasets:
      # - name: "mozilla-foundation/common_voice_11_0"
      #   config: "ja"
      #   split: "train"
      #   text_column: "sentence"
      - name: "japanese-asr/ja_asr.jsut_basic5000"
        config: "default"
        split: "train"
        text_column: "transcription"
      - name: "google/fleurs"
        config: "ja_jp"
        split: "train"
        text_column: "raw_transcription"
      - name: "reazon-research/reazonspeech"
        config: "tiny"
        split: "train"
        text_column: "transcription"
  eval:
    datasets:
      # - name: "mozilla-foundation/common_voice_11_0"
      #   config: "ja"
      #   split: "validation"
      #   text_column: "sentence"
      - name: "japanese-asr/ja_asr.jsut_basic5000"
        config: "default"
        split: "val"
        text_column: "transcription"
      - name: "google/fleurs"
        config: "ja_jp"
        split: "val"
        text_column: "raw_transcription"
      - name: "reazon-research/reazonspeech"
        config: "tiny"
        split: "val"
        text_column: "transcription"
  test:
    datasets:
      # - name: "mozilla-foundation/common_voice_11_0"
      #   config: "ja"
      #   split: "test"
      #   text_column: "sentence"
      - name: "japanese-asr/ja_asr.jsut_basic5000"
        config: "default"
        split: "test"
        text_column: "transcription"
      - name: "google/fleurs"
        config: "ja_jp"
        split: "test"
        text_column: "raw_transcription"
#      - name: "reazon-research/reazonspeech"
#        config: "all"
#        split: "test"
#        text_column: "transcription"
