dataset_config:
  train:
    datasets:
      # - name: "mozilla-foundation/common_voice_11_0"
      #   config: "ja"
      #   split: "train"
      #   text_column: "sentence"
      - name: "google/fleurs"
        config: "ja_jp"
        split: "train"
        text_column: "raw_transcription"
  val:
    datasets:
      # - name: "mozilla-foundation/common_voice_11_0"
      #   config: "ja"
      #   split: "val"
      #   text_column: "sentence"
      - name: "google/fleurs"
        config: "ja_jp"
        split: "val"
        text_column: "raw_transcription"
  test:
    datasets:
      # - name: "mozilla-foundation/common_voice_11_0"
      #   config: "ja"
      #   split: "test"
      #   text_column: "sentence"
      - name: "google/fleurs"
        config: "ja_jp"
        split: "test"
        text_column: "raw_transcription"